[project]
name = "wallabag-importer"
version = "0.1.0"
description = "A Python tool that automatically imports RSS/Atom feed entries into your Wallabag instance"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "feedparser>=6.0.11",
    "requests>=2.32.4",
]
